### ISSUE TITLE
Add support for excluding some tests per-stream

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#1002]
With the new `rhel-9.4` and `c9s` streams added in https://github.com/openshift/os/pull/1445, we need to be able to run kola tests but skipping those that are specific to OpenShift. Those ones have already been tagged with `openshift` ([example](https://github.com/coreos/coreos-assembler/pull/3741)). So basically, we need a stream-level knob that in practice boils down to `--tag !openshift` when we run kola.

E.g. something like:

```yaml
streams:
  rhel-9.4:
    skip_kola_tags: [openshift]
```

?

(So at least it's generic over the tag name.)

**Comment by marmijo** [comment]
I opened a few PRs to solve this issue:

- https://github.com/coreos/coreos-ci-lib/pull/159
- https://github.com/coreos/fedora-coreos-pipeline/issues/1002
- Internal rhcos-art-pipcfg to skip openshift tag on c9s and rhel-9.2 streams

**Comment by marmijo** [comment]
Closing as completed.
