### ISSUE TITLE
issues when running in communishift (OCP 4.1 in fedora infra) 

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#134]
A few things to note:

- I was not able to log in to jenkins using the login with openshift click box. I got some oath error. I think our pinned version of jenkins might be causing an issue because if I removed the pinning and used the default jenkins imagestreams I didn't have this problem. 
- There aren't any `ReadWriteOnce` PVs allocated in the environment so I had to change the PVCs to ask for `ReadWriteMany`.

For the first issue I think we can just figure out and update out jenkins reference (when we do this we want to make 100% certain is still works in CCI). 

For the 2nd issue we might be able to switch our PVCs to `ReadWriteMany` (not sure of the implications or if CCI can handle that) or we may be able to get Fedora Infra to offer `ReadWriteOnce`.

**Comment by jlebon** [comment]
> For the first issue I think we can just figure out and update out jenkins reference

Yeah, probably time we bumped to the latest LTS anyway.

**Comment by dustymabe** [comment]
One other issue with communishift:

- there's no `/dev/kvm` yet

I opened [a request](https://pagure.io/fedora-infrastructure/issue/8208) with fedora infra to see if we can get it added.

**Comment by dustymabe** [comment]
> One other issue with communishift:
> 
>     * there's no `/dev/kvm` yet
> 
> 
> I opened [a request](https://pagure.io/fedora-infrastructure/issue/8208) with fedora infra to see if we can get it added.

This is no longer an issue. The request was granted.

**Comment by jlebon** [comment]
Closing as stale. Feel free to re-open if not.
