### ISSUE TITLE
Move repo to coreos org

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#15]
We should do that soon-ish. The earlier we do, the less painful it'll be to update the various references.

**Comment by dustymabe** [comment]
+1 will try to do that soon

**Comment by cgwalters** [comment]
SGTM (though I wonder if we should s/-ci/-pipeline/ but that's optional)

**Comment by dustymabe** [comment]
yeah. pipeline wouldn't be bad IMHO

**Comment by bgilbert** [comment]
SGTM.

**Comment by jlebon** [comment]
`fedora-coreos-pipeline` WFM

**Comment by dustymabe** [comment]
https://github.com/coreos/fedora-coreos-pipeline exists now :fireworks:
