### ISSUE TITLE
Codify IAM permissions required for Kola tests

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#174]
Right now, we're using two IAM accounts. One for the building part (upload & AMI creation), and one for running Kola tests in AWS. The IAM permissions for the former are available under https://github.com/coreos/fedora-coreos-pipeline/blob/b9063d54bcd62694ab332c1096419b0bba9e526a/docs/aws-iam-policies/prod-account. But we don't currently have the same thing for the latter.

**Comment by dustymabe** [comment]
I think some of these may be in the Fedora ansible repo now. Let me look and see if I can find them.

**Comment by dustymabe** [comment]
Yep. The prod ones are in the fedora ansible repo and the community account ones are in this repo. All of it is linked from [the README](https://github.com/coreos/fedora-coreos-pipeline/blob/main/docs/aws-iam-policies/README.md).
