### ISSUE TITLE
Build should time out if it takes more than X hours

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#195]
E.g. we had a build recently just hang on S3 uploads.

Or could try to be fancier and do different timeouts per stage. But a big wrapping timeout would work to begin with.

**Comment by dustymabe** [comment]
👍

**Comment by dustymabe** [comment]
hit this again.. I just killed https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/11960/  which has been running almost a day.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-pipeline/pull/214
