### ISSUE TITLE
Gracefully handle `image.yaml` only changes

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#244]
Right now if the RPM input didn't change but `image.yaml` did, we error out like this:

```
error: Importing 5d7ec2a8c0a38dbf8e6ebbf04435d25393c3ba1b8c15b05990d63393cda97ec3.dirtree: linkat: No such file or directory
```

I think what's going on here is that cosa wants to build the image, but there is no local OSTree so it fails.

Ideally, what we'd do is detect this case and fetch the OSTree tarball from the previous release before continuing. In practice... this happens pretty rarely so it might not be worth handling this. At least for now though we should detect it and exit gracefully.

**Comment by cgwalters** [comment]
Dup of https://github.com/coreos/coreos-assembler/issues/972
