### ISSUE TITLE
break bump-lockfile into multiple jobs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#331]
It currently updates both testing-devel and next-devel in a single job. If one of these streams fails for any reason then bump-lockfile looks like the entire job fails, even though half of it succeeded. Having them co-mingled means that it's also hard to tell which of the two failed (or maybe both failed?) and in what way. Let's break them into two separate jobs to ease up on the confusion.

**Comment by jlebon** [comment]
Yeah, and it doesn't help that the BlueOcean view gets super confused by the parallel + nested stages we got going on in that job.

Easiest way to do this is: "un-parallelize" bump-lockfile, drop the cron trigger, and make it take the target stream as a parameter. Then add another job with a cron trigger which just triggers bump-lockfile jobs for each stream.
