### ISSUE TITLE
Don't require rsync'ing everything to build and prune

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#38]
Right now, because our only way to interact with the artifact server is through rsync, we have to rsync everything in, build, prune, then rsync everything out. A new `buildprep` was added in coreos-assembler to allow building without having everything sync'ed in: https://github.com/coreos/coreos-assembler/pull/249. But because of pruning, we do still need to rsync everything. IOW, if you have something like this:

```
$ ls mydir/
foo/
bar/
baz/
```

I'm not sure if it's possible to delete `mydir/foo/` on the remote server without having all of `mydir/` synced in.

For the OSTree repo at least, we'll likely need to always rsync in everything because pruning is done by `ostree prune`. Though if we can solve the above issue, we could at least avoid having to sync in all of `builds/`, which is where the bulk of the storage lies anyway.

Once we do this, we'll be able to better decouple how many builds we want to keep from how large our PVC is.

**Comment by jlebon** [comment]
> I'm not sure if it's possible to delete mydir/foo/ on the remote server without having all of mydir/ synced in.

Investigating this.

**Comment by jlebon** [comment]
Hmm, so one way to do this is with the `--filter 'protect N/*'` option which then has to be repeated for each build we want to keep. That will do the trick, though looking some more (it's incredible how complex the rsync filter rules are).

**Comment by dustymabe** [comment]
> I'm not sure if it's possible to delete `mydir/foo/` on the remote server without having all of `mydir/` synced in.

IOW, "how do I delete a remote directory using rsync?" ? Yeah I wish there was a really easy way just to say. I want xyz directory deleted and have it happen without having to do it indirectly

**Comment by jlebon** [comment]
Gonna close this one in favour of #60.
