### ISSUE TITLE
run aarch64/x86_64 openstack tests in different regions

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#422]
Right now we are starting to get blocked on openstack tests (i.e. if we run `stable`, `testing`, `next` at about the same time then we have 6 openstack runs that need to happen and they currently run serially because of quota limits). Let's run the `x86_64` tests in the `ams1` region so we can execute tests in parallel.

I believe this will at least require some work in coreos-assembler to be able to specify a region to `ore` for the image upload and override what is in the config.

**Comment by dustymabe** [comment]
I think @jmarrero is going to work on this

**Comment by jmarrero** [comment]
yes, adding this to my TO-DO for next week. I can't seem to assign myself to the issue here.

**Comment by bgilbert** [comment]
@jmarrero I've added you to the relevant GitHub teams and you're assignable now.

**Comment by dustymabe** [comment]
Once https://github.com/coreos/coreos-assembler/pull/2560 merges we'll then be able to update [kola-openstack.Jenkinsfile](https://github.com/coreos/fedora-coreos-pipeline/blob/main/jobs/kola-openstack.Jenkinsfile) to switch on the architecture and run the `x86_64` tests in the `ams1` region and the `aarch64` tests in the `ca-ymq-1` region.

As part of this we'll want to remove the [disableConcurrentBuilds()](https://github.com/coreos/fedora-coreos-pipeline/blob/00924af564a7ec2f4c465975146d6dea71c3fb30/jobs/kola-openstack.Jenkinsfile#L11) and add in a lock ([example](https://github.com/coreos/fedora-coreos-pipeline/blob/00924af564a7ec2f4c465975146d6dea71c3fb30/jobs/multi-arch-pipeline.Jenkinsfile#L133)) so we don't run more than one run in a particular region at the same time (i.e. we could hit quota limits).

**Comment by jmarrero** [comment]
@dustymabe so does that mean that I am hard coding on  `kola-openstack.Jenkinsfile` what region to go on x86_64 and aarch64? Or are we passing that from somewhere else? We don't build other args?

**Comment by dustymabe** [comment]
> does that mean that I am hard coding on `kola-openstack.Jenkinsfile` what region to go on x86_64 and aarch64?

yes, I believe so.

**Comment by dustymabe** [comment]
Looks like we also need to update the kola call too. see an example in c4bdf1f

**Comment by dustymabe** [comment]
This should be fixed now with https://github.com/coreos/fedora-coreos-pipeline/pull/426 merged
