### ISSUE TITLE
Investigate sync-stream-metadata not automatically triggering

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#444]
Had to do this manually after the releases this week.

**Comment by jlebon** [comment]
This is fixed. The issue was due to rerunning the seed job recently, but we hadn't actually updated the configmap since https://github.com/coreos/fedora-coreos-pipeline/pull/378, so it redefined all jobs which wiped the triggers. The job ran once now, so its trigger was re-instated.

**Comment by dustymabe** [comment]
Thanks for looking at this @jlebon!
