### ISSUE TITLE
Strengthen `build-arch` rebuild capabilities

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#566]
Right now, if `build-arch` fails, one can *mostly* rerun it with the same parameters. There is one gotcha: if the failure happens at any point after the `Archive` step, the artifacts for the given build ID and arch will already exist.

We should strengthen the job so that it handles this window better.

**Comment by jlebon** [comment]
One simple solution @dustymabe and I we came up with is to check upfront if the artifacts already exist, and if so just skip straight to the `Sign Images` step.

**Comment by jlebon** [comment]
A temporary hack on this is to have a `salvage-build` job that we can run manually that just fetches the artifacts of a build, signs them, emits the compose repo import, and schedules the follo-wup kola jobs.

**Comment by jschintag** [comment]
One option is to have the steps that notifies the ostree repo to be a warning instead of a failure, saving us from having to run cloud and update tests manually for the build.
