### ISSUE TITLE
Allow concurrent builds

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#68]
Right now, Jenkins tries to be smart and reuse the same container between builds. We don't want that because it means we can't have e.g. a devel build running at the same time as a prod build, even though they don't intersect in any way.

Probably need to tweak some of these settings:
https://github.com/jenkinsci/kubernetes-plugin#over-provisioning-flags

**Comment by jlebon** [comment]
Small refinement upon further inspection; it *does* spawn multiple containers if the pod spec is different, but not if they're the same it seems. In the devel case, it more often than not isn't the same (if e.g. one is running with a custom pipeline or COSA), though it could be.

Another reason to look into this is so that we can have multiple prod streams running at the same time (though we need to make sure we share cache space smartly).

**Comment by jlebon** [comment]
#76 drops the `disableConcurrentBuilds()`, but we still need to tweak Jenkins flags to fully enable this.

**Comment by dustymabe** [comment]
> tweak Jenkins flags to fully enable this.

which jenkins flags?

**Comment by jlebon** [comment]
> which jenkins flags?

See the link in the first comment. Should be pretty straightforward, just haven't gotten around to testing it out.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-pipeline/pull/194

**Comment by jlebon** [comment]
This was fixed.
