### ISSUE TITLE
Implementing streams

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#75]
So, there are various ways to implement multiple streams in the pipeline. The way I'm thinking of is to keep `fedora-coreos-pipeline` as a parameterized job without any triggers and have one upstream job per each stream that simply fires off a build of `fedora-coreos-pipeline` with the right parameters. Those upstream jobs can then have their own triggers defined, and e.g. fire off more stream-specific follow-up jobs after the main build if required.

This matches the PAPR "executor" model which has worked pretty well, and the CL model as well I think.

Thoughts?

**Comment by jlebon** [comment]
Another approach which leverages OCP a bit more is to have one pipeline buildconfig per stream, and just have the core pipeline Groovy code as a shared library. I think this is a bit closer to what RHCOS does.

**Comment by dustymabe** [comment]
so the two options are

1. a main job that is parameterized that is called with options by other jobs (one for each stream) that have their own triggers
2. each stream has its own job and triggers and calls a common library to do the heavy lifting

My first reaction was that I like option `1.` better (seems easier to maintain) but it may make it harder to experiment with the pipeline (i.e. if you change the main job you change it for all of them).

Anybody else with thoughts on this?

**Comment by jlebon** [comment]
I was really intrigued by the approach in https://github.com/coreos/jenkins-os, esp. https://github.com/coreos/jenkins-os/blob/master/init.groovy. It solves the bootstrap problem in a straightforward way, but I don't like that it still requires copy/pasting.

The bootstrap problem is:
1. how to get the jobs defined in Jenkins in the first place
2. how to get them to fire at least once so that their configured triggers are applied

The goal I think we should aim for here is having zero configuration live solely in the Jenkins PVC, i.e. we shouldn't have to interact with the Jenkins UI at all post-deployment to finish set up. The git repo should be all there is.

Using OpenShift buildconfigs pipelines solves these issues nicely. But at the same time, it's likely we will have more jobs added in the future (e.g. all the automation around git pushes) and I'm hesitant about having one BC for each of those. What I'm playing with right now is a combination of the CL idea with OpenShift: we have a `jobs/` directory in this repo with e.g.
- `pipeline.groovy`: Main job, no triggers. Manually triggered for prod builds.
- `pipeline-devel.groovy`: Triggers on git pushes to devel branches. Triggers main job with the correct devel stream.
- `pipeline-mechanical.groovy`: Triggers on timer and git pushes to mechanical branches. Triggers main job with the correct mechanical stream.
- `any-other-job-we-want.groovy`

And then have a single buildconfig pipeline that simply walks the `jobs/` dir and creates the jobs. So to set up from scratch would essentially be similar to today: `oc new-app ...`, then e.g. `oc start-build fedora-coreos-job-creator`.

The cosa logic is thus in the main job only, which does make things slightly complicated if we want to have different logic for a specific stream (how lockfiles are handled is the main one that comes to mind; otherwise I think we should try to keep differences at a minimum). At the same time, having all the logic in one place is helpful too. And of course, the `pipeline-devel` and `pipeline-mechanical` jobs could trigger follow-up jobs as required. Not something we couldn't change later anyway too.

How does this intersect with the developer workflow? I think we can just set an annotation on the `job-creator` bc so it does what we want (e.g. it could create `pipeline.groovy` only and prefix it like today).

**Comment by jlebon** [comment]
Got a prototype in #76 which just takes the easy path for now using:

> Using OpenShift buildconfigs pipelines solves these issues nicely

I think it's worth trying out before going with the meta "job creator" bc approach. (And plus being able to manage them from the CLI with `oc` is really nice).

**Comment by jlebon** [comment]
Fixed in #76.
