### ISSUE TITLE
create a job to aid in multi-arch builder access

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#803]
We recently discussed our limited access to multi-arch for most of our team members. We have our multi-arch builders, but managing access can be complicated. We could just use the pipeline itself to spawn a remote session on a builder and the user can then grab a shell via OpenShift to do testing. The remote sessions would be auto-garbage collected after a period of time.

**Comment by aaradhak** [comment]
@dustymabe 
Summarizing the requirements as discussed in the meeting. Kindly review if there are any missing points in the requirements.

Requirements:
- pod name includes the name of the person who ran the job
       - i.e. user-devpod-2023101abc
- pod/job times out after X hours (configurable?)
- starts remote session on multi-arch builder and does a few convenience things
       - runs tmux (so that the session can be connected to by the user)
           - user uses openshift webui or CLI to connect to pod and re-attach to tmux
           - tmux window offers two panes
                  - one where the remote session is already set up. 
                  - running cosa just works in tmux. 
- Run cosa init

**Comment by aaradhak** [comment]
Completed the task of adding debug pod job .
