### ISSUE TITLE
Add Secure Execution builder host key to enable reboots in tests

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#833]
From https://github.com/coreos/coreos-assembler/pull/3384#discussion_r1124933887:

> Hmm, in a follow-up, we could do something similar on the s390x builder we do for the genprotimg qcow2 where we put the builder's hostkey in a volume and then mount it into the cosa container at e.g. `/data.secex-hostkey` or something. Then, our test would even be able to reboot and test upgrades and verify that the system comes up fine.

**Comment by jlebon** [comment]
Bundling it in the existing volume SGTM. :+1:

**Comment by jschintag** [comment]
I have added the hostkey of the LPAR into the volume:
```
$ tree /data.secex/
/data.secex/
├── genprotimgvm.qcow2
└── hostkeys
    └── HKD-<serial>.crt

2 directories, 2 files
```
So for the future the syntax would be `hostkeys/HKD-*.crt` for adding new Hostkeys.

**Comment by jlebon** [comment]
Thanks! Let's close this then.
