### ISSUE TITLE
Run Secure Execution tests

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#834]
We added one in https://github.com/coreos/fedora-coreos-config/pull/2283 and added support for running it in cosa in https://github.com/coreos/coreos-assembler/pull/3384.

**Comment by nikita-dubrovskii** [comment]
@jlebon, as all secex tests are merged shouldn't we close this issue now?

**Comment by jschintag** [comment]
The tests are currently not running due to coreos-assembler not supporting them in 4.12:
https://github.com/coreos/fedora-coreos-pipeline/pull/866

**Comment by c4rt0** [comment]
All secex tests are now running, this one can now be closed as complete.
