### ISSUE TITLE
bodhi-updates flipflopping upgraded vs downgraded packages

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#85]
Looking at the build history for `bodhi-updates` in [the browser](https://builds.coreos.fedoraproject.org/browser), one can easily see there seems to be an issue where `bodhi-updates` sometimes upgrades a set of packages, and then the next builds downgrades them, and then the next build re-upgrades then, etc...

I think what's happening there is that we're hitting different mirrors each time and some of them might still have older packages as content gets propagated across the network (see e.g. https://admin.fedoraproject.org/mirrormanager/propgation/f30_updates). An easy fix is using `dl.fedoraproject.org` though that puts more stress on the Fedora infra. We do cache rpmmd and packages though, so it wouldn't be *that* bad either.

Another approach would be to have our own local mirror too. CentOS CI might even already have one.

**Comment by dustymabe** [comment]
> An easy fix is using `dl.fedoraproject.org` though that puts more stress on the Fedora infra. We do cache rpmmd and packages though, so it wouldn't be _that_ bad either.

That is the most practical approach.



> Another approach would be to have our own local mirror too. CentOS CI might even already have one.

If CentOS CI does have its own mirror then let's use that. If not then let's not worry about it.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/109

**Comment by jlebon** [comment]
Reverted in https://github.com/coreos/fedora-coreos-config/pull/111

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/116

**Comment by cgwalters** [comment]
Another approach is for rpm-ostree to ignore "downgrades" in repos by comparing generation timestamps.  (We'd need a `--force-downgrade` flag though)

**Comment by jlebon** [comment]
This is fixed now.
