### ISSUE TITLE
bodhi-updates failing due to missing zincati

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#88]
```
Importing rpm-md... done
Packages not found: zincati
```

The reason is that we don't source `coreos-pool` for bodhi-updates (see https://github.com/coreos/fedora-coreos-config/pull/104#issuecomment-502174629) and Zincati right now is only in `coreos-pool`.

**Comment by jlebon** [comment]
@rfairley Can we submit Zincati to Bodhi?

**Comment by rfairley** [comment]
Ahh, yep - missed this. Doing that now.

**Comment by rfairley** [comment]
Update submitted for F30: https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2019-74e36a7052

**Comment by jlebon** [comment]
This is fixed.
