### ISSUE TITLE
Support specifying env vars in the config.yaml 

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#939]
Once in a while, we need to be able to define env vars as part of the build process. Let's add a pipecfg knob for this to make it easier in the future. E.g.

```yaml
env:
    FOO: bar
```

Roughly, we just need to plumb it in two locations: when defining the cosa pod in our jobs, and in the multi-arch case, wiring it through to the remote cosa pod (see first bullet of https://github.com/coreos/fedora-coreos-pipeline/pull/938#issuecomment-1836516967).

**Comment by dustymabe** [comment]
Note that if we implemented this we could implement https://github.com/coreos/fedora-coreos-pipeline/pull/921 using this more generic option and rip out the specific `use_osbuild` config entry.

**Comment by dustymabe** [comment]
This is done now with:

- https://github.com/coreos/coreos-ci-lib/pull/157         
- https://github.com/coreos/coreos-assembler/pull/3704     
- https://github.com/coreos/fedora-coreos-pipeline/pull/952
